name: Update VacinaManaus data CI

on:
  schedule:
    - cron: "00 03 * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download the latest pdf
      run: |
        make download-data
    - name: Extract
      run: |
        make extract-data
    - name: Process
      run: |
        make process-data
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: now
      with:
        format: YYYYMMDDHHmm
        utcOffset: "-04:00"
    - name: Set branch name
      run: echo "branch_name=update-data-${{steps.now.outputs.formattedTime}}" >> $GITHUB_ENV
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'chore: Atualiza os dados com a última lista divulgada ${{steps.now.outputs.formattedTime}}'
        title: 'Atualiza os dados com a última lista divulgada ${{steps.now.outputs.formattedTime}}'
        branch: ${{ env.branch_name }}

